apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
- path: patch.yaml  

configMapGenerator:
- name: app-properties
  files:
  - application.properties
  literals:
    - EXTRA_ARG=demo
  options:
    disableNameSuffixHash: true  