apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  template:
    spec:
      containers:
        - name: busybox
          env:
            - name: VAR
              valueFrom:
                configMapKeyRef:
                  name: app-properties
                  key: EXTRA_ARG