apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

namePrefix: dev-  

commonAnnotations:
  updatedBy: kustomize

commonLabels:
  owner: test-company
  serverVersion: v1